# Generated by Django 5.1.5 on 2025-02-14 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0002_todo_updated_at_todorepeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todorepeat',
            name='todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_repeats', to='to_do.todo'),
        ),
        migrations.CreateModel(
            name='ToDoHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_histories', to='to_do.todo')),
            ],
        ),
    ]
