# Generated by Django 5.1.5 on 2025-02-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0005_alter_todohistory_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
