# Generated by Django 5.1.5 on 2025-03-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0007_alter_todo_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryMiddleware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
