# Generated by Django 5.1.5 on 2025-03-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0008_historymiddleware'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetTodos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='HistoryMiddleware',
        ),
    ]
