# Generated by Django 5.1.5 on 2025-03-05 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0009_resettodos_delete_historymiddleware'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resettodos',
            options={'verbose_name_plural': 'reset_todos'},
        ),
        migrations.AlterModelOptions(
            name='todohistory',
            options={'verbose_name_plural': 'todo_histories'},
        ),
    ]
