# Generated by Django 5.1.5 on 2025-05-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0010_alter_resettodos_options_alter_todohistory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todorepeat',
            name='repeat_day',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
